services:
  bgb-solr:
    image: solr:9.4
    container_name: bgb-solr
    ports:
      - "8984:8983"  # Use different port to avoid conflicts with other Solr instances
    environment:
      - SOLR_OPTS=-Dsolr.log.level=INFO
    volumes:
      - bgb_solr_data:/var/solr
    command:
      - solr-precreate
      - bgb_core
    networks:
      - bgb_network

  bgb-blazegraph:
    image: lyrasis/blazegraph:2.1.5
    container_name: bgb-blazegraph
    ports:
      - "9999:8080"  # Blazegraph runs on port 8080
    environment:
      - JAVA_OPTS=-Xmx2g -Xms512m
    volumes:
      - bgb_blazegraph_data:/var/lib/blazegraph
      - ./kg_curation/output:/data:ro  # Mount TTL file directory as read-only
    networks:
      - bgb_network

volumes:
  bgb_solr_data:
    driver: local
  bgb_blazegraph_data:
    driver: local

networks:
  bgb_network:
    driver: bridge